Repository Hallym-LIKELION/HallymFestival2023-Backend-, pull requests merged in 2023-04, with the labels that each got.

#60 notice 목록 조회와 검색 조회에 페이징 추가
  src/main/java/com/hallym/festival/domain/notice/controller/NoticeController.java
  src/main/java/com/hallym/festival/domain/notice/repository/NoticeRepository.java
  src/main/java/com/hallym/festival/domain/notice/service/NoticeServicelmpl.java
  src/test/java/com/hallym/festival/service/NoticeServiceTests.java
Labels: feat, MIJIN

#62 meun is_deleted가 false만 나올 수 있도록 변경
  src/main/java/com/hallym/festival/domain/menu/repository/MenuRepository.java
  src/main/java/com/hallym/festival/domain/menu/service/MenuServicelmpl.java
  src/main/resources/application.yml
Labels: docs, MIJIN

#64 방문자 수 날짜별 집계, IP Controller 생성
  src/main/java/com/hallym/festival/domain/comment/controller/CommentController.java
  src/main/java/com/hallym/festival/domain/comment/dto/CommentPasswordDTO.java
  src/main/java/com/hallym/festival/domain/comment/dto/CommentReportedResponseDTO.java
  src/main/java/com/hallym/festival/domain/comment/dto/CommentRequestDTO.java
  src/main/java/com/hallym/festival/domain/comment/dto/CommentResponseDTO.java
  src/main/java/com/hallym/festival/domain/comment/service/CommentService.java
  src/main/java/com/hallym/festival/domain/comment/service/CommentServiceImpl.java
  src/main/java/com/hallym/festival/domain/likes/controller/LikeController.java
  src/main/java/com/hallym/festival/domain/likes/dto/LikesResponseDTO.java
  src/main/java/com/hallym/festival/domain/likes/dto/LikesResponseTopDTO.java
  src/main/java/com/hallym/festival/domain/likes/service/LikeService.java
  src/main/java/com/hallym/festival/domain/likes/service/LikeServiceImpl.java
  src/main/java/com/hallym/festival/domain/totalvisit/controller/TotalVisitController.java
  src/main/java/com/hallym/festival/domain/totalvisit/dto/TotalVisitCountDTO.java
  src/main/java/com/hallym/festival/domain/totalvisit/entity/TotalVisit.java
  src/main/java/com/hallym/festival/domain/totalvisit/repository/TotalVisitRepository.java
  src/main/java/com/hallym/festival/domain/totalvisit/service/TotalVisitService.java
  src/main/java/com/hallym/festival/domain/totalvisit/service/TotalVisitServiceImpl.java
  src/main/java/com/hallym/festival/domain/visitcomment/controller/VisitCommentController.java
  src/main/java/com/hallym/festival/domain/visitcomment/dto/VisitCommentPasswordDTO.java
  src/main/java/com/hallym/festival/domain/visitcomment/dto/VisitCommentReportedResponseDTO.java
  src/main/java/com/hallym/festival/domain/visitcomment/dto/VisitCommentRequestDTO.java
  src/main/java/com/hallym/festival/domain/visitcomment/dto/VisitCommentResponseDTO.java
  src/main/java/com/hallym/festival/domain/visitcomment/service/VisitCommentService.java
  src/main/java/com/hallym/festival/domain/visitcomment/service/VisitCommentServiceImpl.java
  src/main/java/com/hallym/festival/global/ip/IpController.java
  src/test/java/com/hallym/festival/service/CommentServiceTest.java
  src/test/java/com/hallym/festival/service/VisitCommentServiceImplTest.java
Labels: feat, refactor, JUYOUNG

#66 ncloud yml 파일 생성 및 git ignore에 숨김파일 설정
  .gitignore
  src/main/resources/application.yml
Labels: chore, JUYOUNG

#67 application-local.yml 추가 및 application.yml 에 include local로 변경
  .gitignore
  src/main/resources/application.yml
Labels: chore

#69 meun, notice 변경
  src/main/java/com/hallym/festival/domain/menu/controller/MenuController.java
  src/main/java/com/hallym/festival/domain/menu/dto/MenuRequestDto.java
  src/main/java/com/hallym/festival/domain/menu/dto/MeunResponseDto.java
  src/main/java/com/hallym/festival/domain/menu/service/MenuService.java
  src/main/java/com/hallym/festival/domain/menu/service/MenuServicelmpl.java
  src/main/java/com/hallym/festival/domain/notice/controller/NoticeController.java
  src/main/java/com/hallym/festival/domain/notice/dto/NoticeDto.java
  src/main/java/com/hallym/festival/domain/notice/service/NoticeService.java
  src/main/java/com/hallym/festival/domain/notice/service/NoticeServicelmpl.java
  src/test/java/com/hallym/festival/service/MenuServiceTests.java
  src/test/java/com/hallym/festival/service/NoticeServiceTests.java
Labels: refactor, MIJIN

#71 단방향 참조 -> 양방향 참조로 변경
  src/main/java/com/hallym/festival/domain/booth/entity/Booth.java
  src/main/java/com/hallym/festival/domain/comment/entity/Comment.java
  src/main/java/com/hallym/festival/domain/commentreport/entity/CommentReport.java
  src/main/java/com/hallym/festival/domain/commentreport/service/CommentReportServiceImpl.java
  src/main/java/com/hallym/festival/domain/likes/dto/LikesResponseDTO.java
  src/main/java/com/hallym/festival/domain/likes/entity/Likes.java
  src/main/java/com/hallym/festival/domain/likes/service/LikeServiceImpl.java
  src/main/java/com/hallym/festival/domain/totalvisit/entity/TotalVisit.java
  src/main/java/com/hallym/festival/domain/visitcomment/entity/VisitComment.java
  src/main/java/com/hallym/festival/domain/visitcommentreport/entity/VisitCommentReport.java
  src/main/java/com/hallym/festival/domain/visitcommentreport/service/VisitCommentReportServiceImpl.java
  src/test/java/com/hallym/festival/repository/BoothRepositoryTests.java
  src/test/java/com/hallym/festival/repository/CommentRepositoryTests.java
Labels: chore, refactor, test, JUYOUNG

#72 Update README.md
  README.md
Labels: chore

#73 meun 양방향 관계로 변경
  src/main/java/com/hallym/festival/domain/menu/controller/MenuController.java
  src/main/java/com/hallym/festival/domain/menu/dto/MenuRequestDto.java
  src/main/java/com/hallym/festival/domain/menu/dto/MeunResponseDto.java
  src/main/java/com/hallym/festival/domain/menu/entity/Menu.java
  src/main/java/com/hallym/festival/domain/menu/service/MenuService.java
  src/main/java/com/hallym/festival/domain/menu/service/MenuServicelmpl.java
  src/main/java/com/hallym/festival/domain/notice/controller/NoticeController.java
  src/main/java/com/hallym/festival/domain/notice/dto/NoticeDto.java
  src/main/java/com/hallym/festival/domain/notice/entity/Notice.java
  src/main/java/com/hallym/festival/domain/notice/service/NoticeService.java
  src/main/java/com/hallym/festival/domain/notice/service/NoticeServicelmpl.java
  src/test/java/com/hallym/festival/repository/MenuRepositoryTests.java
  src/test/java/com/hallym/festival/service/MenuServiceTests.java
  src/test/java/com/hallym/festival/service/NoticeServiceTests.java
Labels: refactor, test, MIJIN
