Repository Hallym-LIKELION/HallymFestival2023-Backend-, pull requests merged in 2023-05, with the labels that each got.

#76 통합빌드 환경세팅
  src/main/java/com/hallym/festival/domain/booth/controller/BoothController.java
  src/main/java/com/hallym/festival/domain/booth/controller/UploadController.java
  src/main/java/com/hallym/festival/domain/comment/controller/CommentController.java
  src/main/java/com/hallym/festival/domain/commentreport/controller/CommentReportController.java
  src/main/java/com/hallym/festival/domain/likes/controller/LikeController.java
  src/main/java/com/hallym/festival/domain/menu/controller/MenuController.java
  src/main/java/com/hallym/festival/domain/notice/controller/NoticeController.java
  src/main/java/com/hallym/festival/domain/totalvisit/controller/TotalVisitController.java
  src/main/java/com/hallym/festival/domain/visitcomment/controller/VisitCommentController.java
  src/main/java/com/hallym/festival/domain/visitcommentreport/controller/VisitCommentReportController.java
  src/main/java/com/hallym/festival/global/exception/WebController.java
  src/main/java/com/hallym/festival/global/ip/IpController.java
Labels: chore

#77 Swagger 문서 설정 추가
  build.gradle
  src/main/java/com/hallym/festival/global/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: DONGHEON

#79 APIUser Domain file 추가
  .gitignore
  src/main/java/com/hallym/festival/domain/Users/dto/APIUserDTO.java
  src/main/java/com/hallym/festival/domain/Users/entity/APIUser.java
  src/main/java/com/hallym/festival/domain/Users/entity/UserRole.java
  src/main/java/com/hallym/festival/domain/Users/repository/APIUserRepository.java
  src/main/java/com/hallym/festival/domain/booth/controller/BoothController.java
  src/main/java/com/hallym/festival/global/config/CustomSecurityConfig.java
  src/main/java/com/hallym/festival/global/config/ServletConfig.java
  src/main/java/com/hallym/festival/global/security/APIUserDetailsService.java
  src/main/java/com/hallym/festival/global/security/filter/APILoginFilter.java
  src/main/java/com/hallym/festival/global/security/handler/APILoginSuccessHandler.java
  src/test/java/com/hallym/festival/repository/APIUserRepositoryTests.java
Labels: DONGHEON

#80 로그인 인증 처리
  .gitignore
  src/main/java/com/hallym/festival/domain/Users/controller/APIUserController.java
  src/main/java/com/hallym/festival/domain/Users/dto/APIUserDTO.java
  src/main/java/com/hallym/festival/domain/Users/entity/APIUser.java
  src/main/java/com/hallym/festival/domain/Users/entity/MemberRole.java
  src/main/java/com/hallym/festival/domain/booth/controller/BoothController.java
  src/main/java/com/hallym/festival/global/config/CustomSecurityConfig.java
  src/main/java/com/hallym/festival/global/security/APIUserDetailsService.java
  src/main/java/com/hallym/festival/global/security/filter/TokenCheckFilter.java
  src/main/resources/application.yml
  src/test/java/com/hallym/festival/repository/APIUserRepositoryTests.java
Labels: fix, chore, feat, refactor, DONGHEON

#83 미사용 클래스 삭제 및 코드 주석 추가
  src/main/java/com/hallym/festival/domain/Users/controller/APIUserController.java
  src/main/java/com/hallym/festival/domain/Users/entity/APIUser.java
  src/main/java/com/hallym/festival/domain/Users/entity/MemberRole.java
  src/main/java/com/hallym/festival/domain/Users/entity/UserRole.java
  src/main/java/com/hallym/festival/domain/Users/repository/APIUserRepository.java
  src/main/java/com/hallym/festival/domain/booth/controller/BoothController.java
  src/main/java/com/hallym/festival/domain/booth/service/BoothService.java
  src/main/java/com/hallym/festival/domain/booth/service/BoothServiceImpl.java
  src/main/java/com/hallym/festival/global/config/CustomSecurityConfig.java
  src/main/java/com/hallym/festival/global/config/RestCorsConfig.java
  src/main/java/com/hallym/festival/global/security/exception/AccessTokenException.java
  src/test/java/com/hallym/festival/service/BoothServiceTests.java
Labels: chore, refactor, DONGHEON

#85 JWT 토큰 생성 시 사용자 유저 권한 정보 반환
  build.gradle
  src/main/java/com/hallym/festival/domain/Users/APIUserService.java
  src/main/java/com/hallym/festival/domain/Users/entity/APIUser.java
  src/main/java/com/hallym/festival/domain/Users/entity/MemberRole.java
  src/main/java/com/hallym/festival/domain/Users/repository/APIUserRepository.java
  src/main/java/com/hallym/festival/domain/booth/controller/UploadController.java
  src/main/java/com/hallym/festival/domain/booth/entity/Booth.java
  src/main/java/com/hallym/festival/domain/notice/entity/Notice.java
  src/main/java/com/hallym/festival/global/security/filter/RefreshTokenFilter.java
  src/main/java/com/hallym/festival/global/security/util/JWTUtil.java
  src/test/java/com/hallym/festival/repository/UserImportTest.java
  src/test/java/com/hallym/festival/service/BoothServiceTests.java
Labels: chore, refactor, test, DONGHEON

#87 querydsl을 이용한 부스검색기능 구현
  src/main/java/com/hallym/festival/domain/booth/dto/PageRequestDTO.java
  src/main/java/com/hallym/festival/domain/booth/service/boothSearch/BoothSearch.java
  src/main/java/com/hallym/festival/domain/booth/service/boothSearch/BoothSearchImpl.java
Labels: feat, JUYOUNG

#88 myBooth API 생성
  src/main/java/com/hallym/festival/domain/booth/controller/BoothController.java
  src/main/java/com/hallym/festival/domain/booth/repository/BoothRepository.java
  src/main/java/com/hallym/festival/domain/booth/service/BoothService.java
  src/main/java/com/hallym/festival/domain/booth/service/BoothServiceImpl.java
  src/test/java/com/hallym/festival/repository/APIUserRepositoryTests.java
  src/test/java/com/hallym/festival/repository/UserImportTest.java
Labels: feat

#89 csv reader를 이용한 사용자 계정 생성
  .gitignore
  src/main/java/com/hallym/festival/domain/Users/dto/APIUserDTO.java
  src/main/java/com/hallym/festival/domain/Users/entity/APIUser.java
  src/main/java/com/hallym/festival/domain/booth/service/BoothServiceImpl.java
  src/main/java/com/hallym/festival/domain/menu/controller/MenuController.java
  src/main/java/com/hallym/festival/domain/menu/dto/MenuResponseDto.java
  src/main/java/com/hallym/festival/domain/menu/service/MenuService.java
  src/main/java/com/hallym/festival/domain/menu/service/MenuServicelmpl.java
  src/test/java/com/hallym/festival/csvImport/PasswordEncoderTest.java
  src/test/java/com/hallym/festival/csvImport/UserImportTest.java
  src/test/java/com/hallym/festival/repository/APIUserRepositoryTests.java
  src/test/java/com/hallym/festival/service/BoothServiceTests.java
  src/test/java/com/hallym/festival/service/MenuServiceTests.java
Labels: DONGHEON

#90 계정 생성 테스트 코드 권한 생성 조건 변경
  src/test/java/com/hallym/festival/csvImport/UserImportTest.java
Labels: refactor, test, DONGHEON

#91 계정 생성 시 부스 생성 조건 코드 수정
  src/test/java/com/hallym/festival/csvImport/UserImportTest.java
Labels: fix, DONGHEON

#92 refactor : UploadController에서 originalName에 "_" 제거 후 link 생성 처리
  src/main/java/com/hallym/festival/domain/booth/controller/UploadController.java
Labels: chore, refactor, test, DONGHEON

#93 hotfix -v1
  src/main/java/com/hallym/festival/domain/booth/controller/BoothController.java
  src/main/java/com/hallym/festival/domain/booth/dto/BoothDTO.java
  src/main/java/com/hallym/festival/domain/booth/repository/BoothRepository.java
  src/main/java/com/hallym/festival/domain/comment/service/CommentServiceImpl.java
  src/main/java/com/hallym/festival/domain/menu/controller/MenuController.java
Labels: fix, bug, JUYOUNG

#94 hotfix - v2
  src/main/java/com/hallym/festival/domain/likes/entity/Likes.java
  src/main/java/com/hallym/festival/domain/likes/repository/LikeRepository.java
  src/main/java/com/hallym/festival/domain/likes/service/LikeServiceImpl.java
Labels: fix, bug

#95 hotfix -v3
  src/main/java/com/hallym/festival/domain/commentreport/entity/CommentReport.java
  src/main/java/com/hallym/festival/domain/commentreport/service/CommentReportServiceImpl.java
  src/main/java/com/hallym/festival/domain/likes/entity/Likes.java
  src/main/java/com/hallym/festival/domain/visitcommentreport/entity/VisitCommentReport.java
  src/main/java/com/hallym/festival/domain/visitcommentreport/service/VisitCommentReportServiceImpl.java
  src/main/java/com/hallym/festival/global/baseEntity/BaseTimeRegDateEntity.java
Labels: feat, refactor, bug, test, JUYOUNG
