Repository Hallym-LIKELION/HallymFestival2023-Backend-, pull requests merged in 2023-03, with the labels that each got.

#1 프로젝트 환경 구성 및 기본 엔티티 테스트
  src/main/java/com/hallym/festival/config/RestCorsConfig.java
  src/main/java/com/hallym/festival/domain/booth/Booth.java
  src/main/java/com/hallym/festival/domain/booth/BoothController.java
  src/main/java/com/hallym/festival/domain/booth/BoothRepository.java
  src/main/java/com/hallym/festival/domain/booth/BoothService.java
  src/main/java/com/hallym/festival/web/HelloController.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/log4j2.xml
  src/test/java/com/hallym/festival/FestivalApplicationTests.java
  src/test/java/com/hallym/festival/HelloControllerTests.java
Labels: chore

#5 [chore] : logging 라이브러리를 logback에서 log4j2로 변경
  build.gradle
Labels: chore

#6 [feat] comment dto 생성 및 서비스 로직 구현
  src/main/java/com/hallym/festival/domain/comment/dto/CommentPasswordDto.java
  src/main/java/com/hallym/festival/domain/comment/dto/CommentRequestDto.java
  src/main/java/com/hallym/festival/domain/comment/dto/CommentResponseDto.java
  src/main/java/com/hallym/festival/domain/comment/entity/Comment.java
  src/main/java/com/hallym/festival/domain/comment/repository/CommentRepository.java
  src/main/java/com/hallym/festival/domain/comment/service/CommentService.java
  src/main/java/com/hallym/festival/security/Encrypt.java
  src/test/java/com/hallym/festival/CommentTest.java
Labels: feat

#8 BaseEntity 생성 및 Booth & Comment Repository 테스트 코드 작성
  build.gradle
  src/main/java/com/hallym/festival/FestivalApplication.java
  src/main/java/com/hallym/festival/domain/booth/Booth.java
  src/main/java/com/hallym/festival/domain/booth/controller/BoothController.java
  src/main/java/com/hallym/festival/domain/booth/entity/Booth.java
  src/main/java/com/hallym/festival/domain/booth/entity/BoothType.java
  src/main/java/com/hallym/festival/domain/booth/repository/BoothRepository.java
  src/main/java/com/hallym/festival/domain/booth/service/BoothService.java
  src/main/java/com/hallym/festival/domain/comment/controller/CommentController.java
  src/main/java/com/hallym/festival/domain/comment/entity/Comment.java
  src/main/java/com/hallym/festival/domain/comment/repository/CommentRepository.java
  src/main/java/com/hallym/festival/domain/comment/service/CommentService.java
  src/main/java/com/hallym/festival/global/baseEntity/BaseTimeEntity.java
  src/main/java/com/hallym/festival/global/config/RestCorsConfig.java
  src/main/java/com/hallym/festival/global/security/Encrypt.java
  src/main/java/com/hallym/festival/web/HelloController.java
  src/main/resources/application.yml
  src/main/resources/log4j2.xml
  src/main/resources/log4j2.yml
  src/test/java/com/hallym/festival/DataSourceTests.java
  src/test/java/com/hallym/festival/FestivalApplicationTests.java
  src/test/java/com/hallym/festival/HelloControllerTests.java
  src/test/java/com/hallym/festival/repository/BoothRepositoryTests.java
  src/test/java/com/hallym/festival/repository/CommentRepositoryTests.java
Labels: chore, feat, refactor, test

#11 Comment 관련 로직 생성
  src/main/java/com/hallym/festival/domain/booth/controller/BoothController.java
  src/main/java/com/hallym/festival/domain/booth/entity/Booth.java
  src/main/java/com/hallym/festival/domain/comment/controller/CommentController.java
  src/main/java/com/hallym/festival/domain/comment/dto/CommentPasswordDto.java
  src/main/java/com/hallym/festival/domain/comment/dto/CommentRequestDto.java
  src/main/java/com/hallym/festival/domain/comment/dto/CommentResponseDto.java
  src/main/java/com/hallym/festival/domain/comment/entity/Comment.java
  src/main/java/com/hallym/festival/domain/comment/repository/CommentRepository.java
  src/main/java/com/hallym/festival/domain/comment/service/CommentService.java
  src/main/java/com/hallym/festival/global/exception/ExceptionCode.java
  src/main/java/com/hallym/festival/global/exception/WrongBoothId.java
  src/main/java/com/hallym/festival/global/exception/WrongCommentId.java
  src/main/java/com/hallym/festival/global/exception/WrongIp.java
  src/main/java/com/hallym/festival/global/security/Encrypt.java
  src/test/java/com/hallym/festival/domain/comment/service/CommentServiceTest.java
  src/test/java/com/hallym/festival/repository/BoothRepositoryTests.java
  src/test/java/com/hallym/festival/repository/CommentRepositoryTests.java
Labels: chore, feat

#13 Like 개발 및 Comment 삭제 실패로직 변경
  src/main/java/com/hallym/festival/domain/booth/controller/BoothController.java
  src/main/java/com/hallym/festival/domain/booth/entity/Booth.java
  src/main/java/com/hallym/festival/domain/comment/controller/CommentController.java
  src/main/java/com/hallym/festival/domain/comment/service/CommentService.java
  src/main/java/com/hallym/festival/domain/likes/dto/LikesResponseDto.java
  src/main/java/com/hallym/festival/domain/likes/entity/Likes.java
  src/main/java/com/hallym/festival/domain/likes/repository/LikeRepository.java
  src/main/java/com/hallym/festival/domain/likes/service/LikeService.java
  src/main/java/com/hallym/festival/global/exception/WrongIp.java
  src/main/java/com/hallym/festival/global/exception/WrongLikesKey.java
  src/main/java/com/hallym/festival/security/Encrypt.java
  src/test/java/com/hallym/festival/repository/BoothRepositoryTests.java
  src/test/java/com/hallym/festival/repository/CommentRepositoryTests.java
Labels: feat, cleanup

#14 Mijin
  src/main/java/com/hallym/festival/domain/menu/controller/MenuController.java
  src/main/java/com/hallym/festival/domain/menu/dto/MenuDto.java
  src/main/java/com/hallym/festival/domain/menu/entity/Menu.java
  src/main/java/com/hallym/festival/domain/menu/repository/MenuRepository.java
  src/main/java/com/hallym/festival/domain/menu/service/MenuService.java
  src/main/java/com/hallym/festival/domain/notice/controller/NoticeController.java
  src/main/java/com/hallym/festival/domain/notice/dto/NoticeDto.java
  src/main/java/com/hallym/festival/domain/notice/entity/Notice.java
  src/main/java/com/hallym/festival/domain/notice/repository/NoticeRepository.java
  src/main/java/com/hallym/festival/domain/notice/service/NoticeService.java
  src/main/resources/application.yml
Labels: feat

#15 부스 게시물 등록 로직 구현한다.
  build.gradle
  src/main/java/com/hallym/festival/domain/booth/controller/BoothController.java
  src/main/java/com/hallym/festival/domain/booth/dto/BoothDTO.java
  src/main/java/com/hallym/festival/domain/booth/entity/Booth.java
  src/main/java/com/hallym/festival/domain/booth/service/BoothService.java
  src/main/java/com/hallym/festival/domain/booth/service/BoothServiceImpl.java
  src/main/java/com/hallym/festival/global/config/ModelMapperConfig.java
  src/main/resources/application.yml
  src/test/java/com/hallym/festival/booth/BoothServiceTests.java
  src/test/java/com/hallym/festival/repository/BoothRepositoryTests.java
Labels: feat

#17 Booth 조회, 수정, 삭제 기능 생성
  src/main/java/com/hallym/festival/domain/booth/controller/BoothController.java
  src/main/java/com/hallym/festival/domain/booth/dto/BoothDTO.java
  src/main/java/com/hallym/festival/domain/booth/dto/PageRequestDTO.java
  src/main/java/com/hallym/festival/domain/booth/dto/PageResponseDTO.java
  src/main/java/com/hallym/festival/domain/booth/entity/Booth.java
  src/main/java/com/hallym/festival/domain/booth/service/BoothService.java
  src/main/java/com/hallym/festival/domain/booth/service/BoothServiceImpl.java
  src/test/java/com/hallym/festival/booth/BoothServiceTests.java
  src/test/java/com/hallym/festival/repository/BoothRepositoryTests.java
Labels: feat, test

#19 comment dto 내용 수정 및 password 적용
  src/main/java/com/hallym/festival/domain/comment/controller/CommentController.java
  src/main/java/com/hallym/festival/domain/comment/dto/CommentPasswordDto.java
  src/main/java/com/hallym/festival/domain/comment/dto/CommentRequestDto.java
  src/main/java/com/hallym/festival/domain/comment/dto/CommentResponseDto.java
  src/main/java/com/hallym/festival/domain/comment/entity/Comment.java
  src/main/java/com/hallym/festival/domain/comment/service/CommentService.java
  src/main/java/com/hallym/festival/global/security/Encrypt.java
Labels: feat

#21 test : 댓글 CRUD Test 코드 작성
  src/main/java/com/hallym/festival/domain/booth/controller/BoothController.java
  src/main/java/com/hallym/festival/domain/comment/dto/CommentPasswordDto.java
  src/main/java/com/hallym/festival/domain/comment/repository/CommentRepository.java
  src/main/java/com/hallym/festival/domain/comment/service/CommentService.java
  src/main/resources/application.yml
  src/test/java/com/hallym/festival/domain/comment/service/CommentServiceTest.java
  src/test/java/com/hallym/festival/repository/CommentRepositoryTests.java
Labels: test

#25 Controller 리턴타입 변경 및 JSON 객체 -> DTO 타입으로 변환
  build.gradle
  src/main/java/com/hallym/festival/domain/booth/controller/BoothController.java
  src/main/java/com/hallym/festival/domain/booth/dto/BoothDTO.java
  src/main/java/com/hallym/festival/domain/booth/entity/BoothType.java
  src/main/java/com/hallym/festival/domain/visitComment/controller/VisitCommentController.java
  src/main/java/com/hallym/festival/domain/visitComment/dto/VisitCommentPasswordDto.java
  src/main/java/com/hallym/festival/domain/visitComment/dto/VisitCommentRequestDto.java
  src/main/java/com/hallym/festival/domain/visitComment/dto/VisitCommentResponseDto.java
  src/main/java/com/hallym/festival/domain/visitComment/entity/VisitComment.java
  src/main/java/com/hallym/festival/domain/visitComment/repository/VisitCommentRepository.java
  src/main/java/com/hallym/festival/domain/visitComment/service/VisitCommentService.java
  src/main/java/com/hallym/festival/global/config/StringRequestDTOConverter.java
Labels: fix, feat, refactor, feadback

#26 Notice create 기능 추가
  src/main/java/com/hallym/festival/domain/notice/controller/NoticeController.java
  src/main/java/com/hallym/festival/domain/notice/dto/NoticeDto.java
  src/main/java/com/hallym/festival/domain/notice/dto/NoticeRequestDto.java
  src/main/java/com/hallym/festival/domain/notice/dto/NoticeResponseDto.java
  src/main/java/com/hallym/festival/domain/notice/entity/Notice.java
  src/main/java/com/hallym/festival/domain/notice/service/NoticeService.java
  src/main/resources/application.yml
  src/test/java/com/hallym/festival/domain/comment/service/NoticeServiceTest.java
Labels: feat

#29 빌더패턴 dto <-> entity 변환을 modelmapper 형식으로 변환
  src/main/java/com/hallym/festival/domain/comment/service/CommentService.java
  src/main/java/com/hallym/festival/domain/likes/service/LikeService.java
Labels: cleanup, refactor

#34 feat : visitComment 방명록 전체 게시물, 생성, 삭제 기능 추가
  build.gradle
  src/main/java/com/hallym/festival/domain/visitComment/controller/VisitCommentController.java
  src/main/java/com/hallym/festival/domain/visitComment/dto/VisitCommentPasswordDto.java
  src/main/java/com/hallym/festival/domain/visitComment/dto/VisitCommentRequestDto.java
  src/main/java/com/hallym/festival/domain/visitComment/dto/VisitCommentResponseDto.java
  src/main/java/com/hallym/festival/domain/visitComment/entity/VisitComment.java
  src/main/java/com/hallym/festival/domain/visitComment/repository/VisitCommentRepository.java
  src/main/java/com/hallym/festival/domain/visitComment/service/VisitCommentService.java
  src/main/resources/application.yml
Labels: feat

#36 신고기능 구현
  src/main/java/com/hallym/festival/domain/comment/controller/CommentController.java
  src/main/java/com/hallym/festival/domain/comment/entity/Comment.java
  src/main/java/com/hallym/festival/domain/comment/service/CommentService.java
  src/main/java/com/hallym/festival/domain/likes/service/LikeService.java
  src/main/java/com/hallym/festival/domain/report/controller/ReportController.java
  src/main/java/com/hallym/festival/domain/report/entity/Report.java
  src/main/java/com/hallym/festival/domain/report/repository/ReportRepository.java
  src/main/java/com/hallym/festival/domain/report/service/ReportService.java
  src/main/resources/application.yml
Labels: feat, refactor

#38 Service 인터페이스를만들어 Impl 하는 구조로 변경
  src/main/java/com/hallym/festival/domain/booth/controller/BoothController.java
  src/main/java/com/hallym/festival/domain/comment/controller/CommentController.java
  src/main/java/com/hallym/festival/domain/comment/service/CommentService.java
  src/main/java/com/hallym/festival/domain/comment/service/CommentServiceImpl.java
  src/main/java/com/hallym/festival/domain/likes/controller/LikeController.java
  src/main/java/com/hallym/festival/domain/likes/service/LikeService.java
  src/main/java/com/hallym/festival/domain/likes/service/LikeServiceImpl.java
  src/main/java/com/hallym/festival/domain/report/controller/ReportController.java
  src/main/java/com/hallym/festival/domain/report/service/ReportService.java
  src/main/java/com/hallym/festival/domain/report/service/ReportServiceImpl.java
  src/test/java/com/hallym/festival/service/CommentServiceTest.java
Labels: refactor

#37 notice 수정, 삭제, 검색 기능 추가
  src/main/java/com/hallym/festival/domain/notice/controller/NoticeController.java
  src/main/java/com/hallym/festival/domain/notice/entity/Notice.java
  src/main/java/com/hallym/festival/domain/notice/repository/NoticeRepository.java
  src/main/java/com/hallym/festival/domain/notice/service/NoticeService.java
  src/test/java/com/hallym/festival/service/NoticeServiceTests.java
Labels: feat

#44 첨부파일 엔티티 생성 및 업로드 기능 구현
  .github/PULL_REQUEST_TEMPLATE.md
  build.gradle
  src/main/java/com/hallym/festival/domain/booth/controller/BoothController.java
  src/main/java/com/hallym/festival/domain/booth/controller/UploadController.java
  src/main/java/com/hallym/festival/domain/booth/dto/upload/UploadFileDTO.java
  src/main/java/com/hallym/festival/domain/booth/dto/upload/UploadResultDTO.java
  src/main/java/com/hallym/festival/domain/booth/entity/Booth.java
  src/main/java/com/hallym/festival/domain/booth/entity/BoothImage.java
  src/main/java/com/hallym/festival/domain/booth/repository/BoothRepository.java
  src/main/java/com/hallym/festival/domain/comment/entity/Comment.java
  src/main/java/com/hallym/festival/domain/comment/repository/CommentRepository.java
  src/main/java/com/hallym/festival/global/config/RestCorsConfig.java
  src/main/resources/application.yml
  src/test/java/com/hallym/festival/repository/BoothRepositoryTests.java
Labels: chore, feat, feadback, test

#42 feat : menu 생성, 목록조회, 삭제 추가
  src/main/java/com/hallym/festival/domain/menu/controller/MenuController.java
  src/main/java/com/hallym/festival/domain/menu/dto/MenuRequestDto.java
  src/main/java/com/hallym/festival/domain/menu/dto/MenuResponseDto.java
  src/main/java/com/hallym/festival/domain/menu/entity/Menu.java
  src/main/java/com/hallym/festival/domain/menu/repository/MenuRepository.java
  src/main/java/com/hallym/festival/domain/menu/service/MenuService.java
  src/main/java/com/hallym/festival/domain/notice/controller/NoticeController.java
  src/main/java/com/hallym/festival/domain/notice/service/NoticeService.java
  src/test/java/com/hallym/festival/service/MenuServiceTests.java
  src/test/java/com/hallym/festival/service/NoticeServiceTests.java
Labels: feat

#46 Querydsl를 이용한 검색과 페이징 기능 구현
  build.gradle
  src/main/java/com/hallym/festival/domain/booth/controller/BoothController.java
  src/main/java/com/hallym/festival/domain/booth/dto/PageRequestDTO.java
  src/main/java/com/hallym/festival/domain/booth/dto/PageResponseDTO.java
  src/main/java/com/hallym/festival/domain/booth/entity/Booth.java
  src/main/java/com/hallym/festival/domain/booth/repository/BoothRepository.java
  src/main/java/com/hallym/festival/domain/booth/repository/boothSearch/BoothSearch.java
  src/main/java/com/hallym/festival/domain/booth/repository/boothSearch/BoothSearchImpl.java
  src/main/java/com/hallym/festival/domain/booth/service/BoothService.java
  src/main/java/com/hallym/festival/domain/booth/service/BoothServiceImpl.java
  src/main/java/com/hallym/festival/domain/comment/repository/CommentRepository.java
  src/main/java/com/hallym/festival/domain/visitComment/controller/VisitCommentController.java
  src/main/java/com/hallym/festival/domain/visitComment/dto/VisitCommentRequestDto.java
  src/main/java/com/hallym/festival/domain/visitComment/dto/VisitCommentResponseDto.java
  src/main/java/com/hallym/festival/domain/visitComment/service/VisitCommentService.java
  src/test/java/com/hallym/festival/repository/BoothRepositoryTests.java
  src/test/java/com/hallym/festival/service/BoothServiceTests.java
Labels: feat

#52 부스 개점 여부 필드 타입을 변경하여 트리거 형태로 구현한다.
  README.md
  build.gradle
  src/main/java/com/hallym/festival/domain/booth/controller/BoothController.java
  src/main/java/com/hallym/festival/domain/booth/controller/advice/RestAdvice.java
  src/main/java/com/hallym/festival/domain/booth/dto/BoothDTO.java
  src/main/java/com/hallym/festival/domain/booth/entity/Booth.java
  src/main/java/com/hallym/festival/domain/booth/entity/BoothActive.java
  src/main/java/com/hallym/festival/domain/booth/repository/BoothRepository.java
  src/main/java/com/hallym/festival/domain/booth/service/BoothService.java
  src/main/java/com/hallym/festival/domain/booth/service/BoothServiceImpl.java
  src/main/java/com/hallym/festival/domain/booth/service/boothSearch/BoothSearch.java
  src/main/java/com/hallym/festival/domain/booth/service/boothSearch/BoothSearchImpl.java
  src/test/java/com/hallym/festival/repository/BoothRepositoryTests.java
  src/test/java/com/hallym/festival/service/BoothServiceTests.java
Labels: refactor, test, DONGHEON

#48 notice 목록조회와 검색할 때 최신에 작성된 것이 나올 수 있도록
  src/main/java/com/hallym/festival/domain/notice/repository/NoticeRepository.java
  src/main/java/com/hallym/festival/domain/notice/service/NoticeService.java
Labels: docs

#55 백오피스 개발(좋아요 수, 부스 댓글 신고, 방명록 신고)
  src/main/java/com/hallym/festival/domain/booth/repository/BoothRepository.java
  src/main/java/com/hallym/festival/domain/comment/controller/CommentController.java
  src/main/java/com/hallym/festival/domain/comment/dto/CommentReportedResponseDto.java
  src/main/java/com/hallym/festival/domain/comment/repository/CommentRepository.java
  src/main/java/com/hallym/festival/domain/comment/service/CommentService.java
  src/main/java/com/hallym/festival/domain/comment/service/CommentServiceImpl.java
  src/main/java/com/hallym/festival/domain/commentreport/controller/CommentReportController.java
  src/main/java/com/hallym/festival/domain/commentreport/service/CommentReportServiceImpl.java
  src/main/java/com/hallym/festival/domain/likes/controller/LikeController.java
  src/main/java/com/hallym/festival/domain/likes/dto/LikesResponseTopDto.java
  src/main/java/com/hallym/festival/domain/likes/repository/LikeRepository.java
  src/main/java/com/hallym/festival/domain/likes/service/LikeService.java
  src/main/java/com/hallym/festival/domain/likes/service/LikeServiceImpl.java
  src/main/java/com/hallym/festival/domain/visitcomment/controller/VisitCommentController.java
  src/main/java/com/hallym/festival/domain/visitcomment/dto/VisitCommentReportedResponseDto.java
  src/main/java/com/hallym/festival/domain/visitcomment/repository/VisitCommentRepository.java
  src/main/java/com/hallym/festival/domain/visitcomment/service/VisitCommentService.java
  src/main/java/com/hallym/festival/domain/visitcomment/service/VisitCommentServiceImpl.java
  src/main/java/com/hallym/festival/domain/visitcommentreport/controller/VisitCommentReportController.java
  src/main/java/com/hallym/festival/domain/visitcommentreport/service/VisitCommentReportServiceImpl.java
  src/test/java/com/hallym/festival/repository/BoothRepositoryTests.java
Labels: feat, refactor, feadback, JUYOUNG

#56 방명록, 부스댓글 신고 responseDto에 생성일 추가
  src/main/java/com/hallym/festival/domain/comment/dto/CommentReportedResponseDto.java
  src/main/java/com/hallym/festival/domain/comment/service/CommentServiceImpl.java
  src/main/java/com/hallym/festival/domain/visitcomment/dto/VisitCommentReportedResponseDto.java
  src/main/java/com/hallym/festival/domain/visitcomment/service/VisitCommentServiceImpl.java
Labels: feat
